spring.application.name=project
spring.datasource.url=jdbc:postgresql://localhost:5432/TourDB
spring.datasource.username=sadra
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
app.security.jwt.secret=4be3ae93bccd9810899c2a267e83f2ff192bb7948ecbd5551ca134f73e55223ec14343c7cfbded9265e8d7702fec536d5a4450bbca9050c58b1f2a9a6daa1ed9
app.security.jwt.expiration-minutes=86400000

# Port
server.port=8081
