spring.application.name=project
spring.datasource.url=jdbc:postgresql://localhost:5432/TourDB
spring.datasource.username=Your_DB
spring.datasource.password=Your_Pass
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
app.security.jwt.secret=Your_Secret_pass
app.security.jwt.expiration-minutes=86400000

# Port
server.port=8080
